# Generated by Django 4.2.2 on 2023-07-06 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(through='orders.OrderDetailsModel', to='products.productmodel'),
        ),
        migrations.AddField(
            model_name='orderdetailsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
        migrations.AddField(
            model_name='orderdetailsmodel',
            name='product_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel'),
        ),
    ]
