# Generated by Django 4.2.2 on 2023-07-06 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='order (sort)')),
                ('name', models.CharField(max_length=50, verbose_name='product')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('price', models.FloatField(verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'apps_product',
                'ordering': ['order', 'id', 'name'],
            },
        ),
    ]
